### Batch Insert

POST http://localhost:8080/api/ChapterService/$batch
Content-Type: multipart/mixed; boundary=batch_1

< ./srv/src/test/resources/batchSuccess.txt

### Check Word Count

GET http://localhost:8080/api/ChapterService/Chapters?$expand=pages

### Batch Insert with error

POST http://localhost:8080/api/ChapterService/$batch
Content-Type: multipart/mixed; boundary=batch_1

< ./srv/src/test/resources/batchError.txt

### Batch Insert with successful and error changeset

POST http://localhost:8080/api/ChapterService/$batch
Content-Type: multipart/mixed; boundary=batch_1

< ./srv/src/test/resources/batchCombined.txt
