bookshop-srv:
  resources:
    requests:
      cpu: 1
      memory: 1G
    limits:
      memory: 1G
  env:
    SPRING_PROFILES_ACTIVE: cloud
  bindings:
    bookshop-hdi-container:
      serviceInstanceFullname: bookshop-hdi-container
    bookshop-uaa:
      serviceInstanceFullname: bookshop-uaa
  health:
    liveness:
      path: actuator/health
    readiness:
      path: actuator/health
bookshop-app:
  resources:
    limits:
      memory: 256M
    requests:
      cpu: 1
      memory: 256M
  bindings:
    bookshop-uaa:
      serviceInstanceFullname: bookshop-uaa
  health:
    liveness:
      path: /
    readiness:
      path: /
bookshop-db:
  resources:
    limits:
      memory: 1G
    requests:
      cpu: 250m
      memory: 1G
  bindings:
    bookshop-hdi-container:
      serviceInstanceFullname: bookshop-hdi-container
bookshop-hdi-container:
  serviceOfferingName: hana
  servicePlanName: hdi-shared
  fullnameOverride: bookshop-hdi-container
bookshop-uaa:
  serviceOfferingName: xsuaa
  servicePlanName: broker
  fullnameOverride: bookshop-uaa